services:
  leo_db:
    image: mongodb/mongodb-atlas-local:8.0
    hostname: leo_db
    ports:
      - 27017:27017
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_INITDB_ROOT_USERNAME}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_INITDB_ROOT_PASSWORD}
    volumes:
      - data:/data/db
      - config:/data/configdb

volumes:
  data:
  config: